### ISSUE TITLE
When an annotation is appended to, the markdown is not re-processed.

### ISSUE THREAD

**Issue by petemounce** [buildkite/feedback#391]
Context: https://buildkite-community.slack.com/archives/C02T53V9H/p1525792493000374

## Tried

Pipeline has several steps that run in parallel.

`pre-command` hook that does roughly:

```bash
echo "* some bullet point" >> annotation.md
cat annotation | buildkite-agent annotate --context build-logs --style info --append
```

## Expected

Annotation gets appended to, creating a list with one rendered bullet per step, creating

```md
* some bullet point
* some bullet point
* some bullet point
```

## Actual

Annotation gets appended to, but markdown is not re-rendered inside web-UI, creating

```md
* some bullet point*some bullet point*some bullet point
```

## Notes

I tried `echo -e`, adding `\n` at beginning/end of echo commands - no difference in outcome.

Agent 3.1.1

**Comment by ticky** [comment]
Hmm, it looks like Markdown is indeed processed, however, [the Buildkite Agent trims whitespace](https://github.com/buildkite/agent/blob/da6e58a23ad89ebe3183a186f2e91b280420ea4e/clicommand/annotate.go#L124-L125), and when appending we do not put line break in between, meaning it’s impossible to put a line break in between annotation chunks.

I’ll look into what we can do to fix this. :)

**Comment by petemounce** [comment]
Would it be reasonable to read STDIN via bufio's line reader instead of ioutil?

**Comment by keithpitt** [comment]
I think I'd be just OK with removing the whitespace trimming from the agent altogether! It probably does more harm than good (and this is a good example). I'd happily accept a PR @petemounce :)

**Comment by petemounce** [comment]
Pretty sure this is fixed via #766.

**Comment by ngocpea** [comment]
Not sure if right place, but i noticed this issue is still present when using `--append`.
