### ISSUE TITLE
Some lines in the build log not breaking properly

### ISSUE THREAD

**Issue by nickbrowne** [buildkite/feedback#48]
![screenshot from 2014-09-04 11 16 51](https://cloud.githubusercontent.com/assets/2295892/4143841/ba3b8ec6-33d2-11e4-9d15-04fa05e4ec82.png)

Seems to have just started happening recently and thought you ought to know

**Comment by keithpitt** [comment]
I think I fixed this a while ago, but forgot to close this issue :D Thanks for letting us know! :dancers:

**Comment by yob** [comment]
Sorry to be the bearer of bad news, but it's still happening on FF31+linux:

![dottsss](https://cloud.githubusercontent.com/assets/8132/7430796/ff9c120c-f05a-11e4-95f4-3d1a0e1797f0.png)

**Comment by yob** [comment]
rspec does it too (not just rubocop)

![rspec](https://cloud.githubusercontent.com/assets/8132/7430848/8013801e-f05b-11e4-93d7-7b2268ae3db8.png)

**Comment by keithpitt** [comment]
Booo...

I pushed a fix I think. Can you confirm?

**Comment by nickbrowne** [comment]
That latest change fixed it for me on FF37+Linux :+1: :ok_hand:

**Comment by keithpitt** [comment]
Woo!

**Comment by yob** [comment]
Thanks!

**Comment by travo** [comment]
Fixed for Firefox — now broken for Chrome (Version 42.0.2311.135 (64-bit)). Sorry Keef.
![buildkite](https://cloud.githubusercontent.com/assets/733/7508338/2d93c54a-f4c2-11e4-9074-9c65667e5395.png)

**Comment by keithpitt** [comment]
![x8ufi_zps62cda975](https://cloud.githubusercontent.com/assets/25882/7512603/791c1184-f4ae-11e4-98c6-98483a3c92db.gif)

**Comment by keithpitt** [comment]
@travo can you email keith@buildkite.com which build that was?

**Comment by travo** [comment]
I want to mark this issue as resolved. How do I raise a ticket for that? Do I need a coversheet of some kind? Thanks @keithpitt

**Comment by toolmantim** [comment]
Firstly you'll need to fill out this NDA @travo…

**Comment by keithpitt** [comment]
![image](https://cloud.githubusercontent.com/assets/25882/7532722/88243226-f56a-11e4-864e-f4f071a68ad6.png)
